### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by jackfruhecolab** [RiFi2k/format-html-in-php#4]
Would be really helpful, if instead of format on save, there was just a command we could invoke with Command-shift-p

As it stands today, it doesn't seem to do anything.

I have some simple code 
````
<?php
echo ("phpstuff here");
?>

<html>
<head>
<title>title</title>
</head>
<body>
<?php 
echo "hello world";
?>
<p>this html should be indented</p>
</body>
</html>
````

None of it is indenting, it's like the extension isn't installed.
I added this to my VScode settings file:

````
"[php]":{
      "editor.formatOnSave": true
    }
````
But no luck.

**Comment by RiFi2k** [comment]
The first part is a planned enhancement same as #3 

The second part is a bug, I only check the initial format on save setting, not the nested format on save under the PHP file specifically.

**Comment by charlesdeb** [comment]
Hmm - I can't even get this to work with this in any of my settings files (user, workspace or project):
```
{
	"editor.formatOnSave": true
}
```
I format the HTML in a PHP file badly, and then hit save - and still nothing happens. Suggestions?

**Comment by RiFi2k** [comment]
@charlesdeb can you send me the full PHP / HTML code from the file you want it to format. Keep the bad formatting. Then also send me any relevant configs that are loading user, project, etc.

If you get me that I'll for sure be able to figure out what is going on.

**Comment by charlesdeb** [comment]
Here is everything that I think is relevant with stuff that I don't want the world to see xxx'ed out.
```
<?php

// Various pieces of html that should go in the <head> item of most pages
// This could ultimately end up in a function that takes various parameters
// such as title, description etc.

include "library/gtm_head.php";

// Note that this includes jQuery on every page - which might give us a wee bit of
// performance hit on those (few?) pages that don't need it.

?>
<meta charset="utf-8"/>
<p>sdjldskj</p>
        <div>skdfskldf  
<div>skdfskldf</div> 
  </div>
<div>skdfskldf</div>
<meta name="robots" content="NOINDEX, NOFOLLOW">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">

     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin">
<link rel="shortcut icon" href="/images/logos/logo-favicon.png" />

<?php
include "helpscout.php";
?>
```

I have removed a few confidential things from it, but the remaining code as well still fails to format.

Folder settings:
```
{
	"editor.formatOnSave": true
}
```

Workspace settings:
```
{
	"folders": [
		{
			"path": "some-folder"
		}
	],
	"settings": {
		// "php-cs-fixer.config": ".php_cs.dist",
		// "php-cs-fixer.formatHtml": true,
		"phpformatter.composer": true,
		"phpformatter.logging": true,
		"phpformatter.arguments": [
			"--config=/some-folder/.php_cs.dist",
			"--verbose"
		],
		// "phpformatter.pharPath":
		//   "/home/charles/.config/composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer",
		"php.suggest.basic": false,
		"editor.formatOnSave": true,
		// as per the intelephense extension recommendation https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
	}
}
```
User settings:
```
{
  // Place your settings in this file to overwrite the default settings
  // Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
  "editor.tabSize": 2,
  // Files
  // Configure glob patterns for excluding files and folders.
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/.DS_Store": true,
    ".meteor/local/": true,
    ".meteor/dev_bundle": true,
    "**/meteor.d.ts": true
  },
  "editor.wordWrap": "on",
  "window.restoreWindows": "one",
  // Controls the font size in pixels.
  "editor.fontSize": 14,
  "vsicons.dontShowNewVersionMessage": true,
  "vsicons.projectDetection.autoReload": true,
  "editor.formatOnPaste": true,
  "editor.renderIndentGuides": true,
  "editor.formatOnType": true,
  // "editor.formatOnSave": true, // would be good, but it monkeys with the blaze templates
  "workbench.colorTheme": "Visual Studio Dark",
  "workbench.iconTheme": "vscode-icons",
  "ruby.lint": {
    "rubocop": true
  },
  "git.enableSmartCommit": true,
  "markdown.preview.fontSize": 16,
  "terminal.integrated.fontSize": 16,
  "eslint.options": {
    "rules": {
      "linebreak-style": 0
    }
  },
  "files.eol": "\n",
  "window.zoomLevel": 1,
  "prettier.eslintIntegration": true,
  "extensions.ignoreRecommendations": false,
  "sync.gist": "xxxxxxxxxx",
  "sync.lastUpload": "xxxxxxx",
  "sync.autoDownload": true,
  "sync.autoUpload": false,
  "sync.lastDownload": "xxxxxxxxxxx",
  "sync.forceDownload": false,
  "sync.anonymousGist": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "sync.askGistName": false,
  "phpformatter.composer": false,
  "phpformatter.pharPath":
    "/home/charles/.config/composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer",
  "phpformatter.logging": true,
  "phpformatter.arguments": [
    "--config=/some-folder/.php_cs.dist","--verbose"
  ],
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "git.confirmSync": false,
  "editor.insertSpaces": false
}

```

PHPFormatter is installed, but I don't think it is working properly either. php cs fixer is installed, but disabled. phpcs code sniffer is installed, but disabled.

**Comment by charlesdeb** [comment]
I think there is something else broken in my vscode installation. When I hit save on that php file, with the developer tools open, I can see this in the console:

```
log.ts:165  WARN Error: listener failed
    at mainThreadSaveParticipant.ts:346
    at Object.g [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1089)
    at n.Class.derive._oncancel._completed (winjs.base.js:1057)
    at e.resolveOk (lazyPromise.ts:65)
    at e._receiveReply (rpcProtocol.ts:283)
    at e._receiveOneMessage (rpcProtocol.ts:210)
    at rpcProtocol.ts:115
    at e.fire (event.ts:140)
    at a (ipc.net.ts:106)
    at Socket.n._socketDataListener (ipc.net.ts:135)
    at emitOne (events.js:116)
    at Socket.emit (events.js:211)
    at addChunk (_stream_readable.js:263)
    at readableAddChunk (_stream_readable.js:250)
    at Socket.Readable.push (_stream_readable.js:208)
    at Pipe.onread (net.js:594)
```

and this shows up in the vscode log:

```
[2018-09-11 21:21:47.859] [exthost1] [error] onWillSaveTextDocument-listener from extension 'rifi2k.format-html-in-php' threw ERROR
[2018-09-11 21:21:47.860] [exthost1] [error] TypeError: Cannot read property 'editor.formatOnSave' of undefined
	at DocumentWatcher.<anonymous> (/home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:36:46)
	at Generator.next (<anonymous>)
	at /home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:3:12)
	at DocumentWatcher.doPreSaveTransformations (/home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:34:16)
	at DocumentWatcher.<anonymous> (/home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:21:46)
	at Generator.next (<anonymous>)
	at /home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:3:12)
	at DocumentWatcher.subscriptions.push.vscode.workspace.onWillSaveTextDocument (/home/charles/.vscode/extensions/rifi2k.format-html-in-php-1.3.6/out/extension.js:18:75)
	at e._deliverEventAsync (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:738:694)
	at e._deliverEventAsyncAndBlameBadListeners (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:737:917)
	at Array.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:737:585)
	at t (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:107:989)
	at n.Class.define.cancel.then (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:86:201)
	at Object.d [as sequence] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:108:89)
	at e.$participateInSave (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:737:477)
	at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```
I have removed all mention of `editor.formatOnSave` from all the settings, but still get the error. It could be a bug I should report to the VSCode folks - or it could be something in your code due to one of my extensions.

That phpcbf thing is alsospitting errors on the console and tells me to check the logs - but there are no meaningul errors in the log either that I can see. Maybe I should remove a whole pile of extensions and try again - but I'm not sure if I can be bothered!

**Comment by RiFi2k** [comment]
@charlesdeb I almost guarantee you have a syntax error in one of your configs.

Go here, https://jsonlint.com/

Paste your configs into that site and validate them, I bet you find out you have a syntax error somewhere.

**Comment by RiFi2k** [comment]
@charlesdeb Yup that's it for sure
```
{
  // Place your settings in this file to overwrite the default settings
  // Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
  "editor.tabSize": 2,
  // Files
  // Configure glob patterns for excluding files and folders.
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/.DS_Store": true,
    ".meteor/local/": true,
    ".meteor/dev_bundle": true,
    "**/meteor.d.ts": true
  },
  "editor.wordWrap": "on",
  "window.restoreWindows": "one",
  // Controls the font size in pixels.
  "editor.fontSize": 14,
  "vsicons.dontShowNewVersionMessage": true,
  "vsicons.projectDetection.autoReload": true,
  "editor.formatOnPaste": true,
  "editor.renderIndentGuides": true,
  "editor.formatOnType": true,
  // "editor.formatOnSave": true, // would be good, but it monkeys with the blaze templates
  "workbench.colorTheme": "Visual Studio Dark",
  "workbench.iconTheme": "vscode-icons",
  "ruby.lint": {
    "rubocop": true
  },
  "git.enableSmartCommit": true,
  "markdown.preview.fontSize": 16,
  "terminal.integrated.fontSize": 16,
  "eslint.options": {
    "rules": {
      "linebreak-style": 0
    }
  },
  "files.eol": "\n",
  "window.zoomLevel": 1,
  "prettier.eslintIntegration": true,
  "extensions.ignoreRecommendations": false,
  "sync.gist": "xxxxxxxxxx",
  "sync.lastUpload": "xxxxxxx",
  "sync.autoDownload": true,
  "sync.autoUpload": false,
  "sync.lastDownload": "xxxxxxxxxxx",
  "sync.forceDownload": false,
  "sync.anonymousGist": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "sync.askGistName": false,
  "phpformatter.composer": false,
  "phpformatter.pharPath":
    "/home/charles/.config/composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer",
  "phpformatter.logging": true,
  "phpformatter.arguments": [
    "--config=/some-folder/.php_cs.dist","--verbose"
  ],
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "git.confirmSync": false,
  "editor.insertSpaces": false
}
```
I pasted that into the JSON lint, you need to remove all the comments from your configs.

**Comment by charlesdeb** [comment]
Yep, that was it. Thanks for your help. It would be nice if VSCode had alerted me to this... Cheers, your extension is now working as expected.

**Comment by RiFi2k** [comment]
One would think, if one of the configs for VSCode had a syntax error, it should probably make every effort to alert you of that. Considering is extremely easy to automate the testing of the file.

**Comment by AdnanNuruddin** [comment]
@RiFi2k  Hi, I'm having a similar error. I've installed the plugin reloaded and restated VSCode multiple times. Yet, nothing happens when I press ctrl + s. 
My user settings:
`{
	"git.autofetch": true,
	"editor.insertSpaces": false,
	"editor.detectIndentation": false,
	"editor.formatOnSave": true
}`
