### ISSUE TITLE
ext requires the setting [php]": {"editor.formatOnSave": true} to work

### ISSUE THREAD

**Issue by AlexSZYDLO** [RiFi2k/format-html-in-php#7]
Hi, thanks for the ext, it's exactly what I was looking for.
However, it took me quite some time to figure out why it was not working in a first place.
It apparently needs the setting :
"[php]": {
        "editor.formatOnSave": true
    }
If the setting is not defined, the ext throws an error and doesn't work, even though I have "editor.formatOnSave": true.
I don't know if this behavior was intended but maybe you should document it.

Thanks anyways,
Alexandre

**Comment by RiFi2k** [comment]
@AlexSZYDLO Thanks for this, it's completely intended to be an "extra" setting in case you didn't want to have format on save on for every file type. I'll look into this error in the case of it being omitted and take care of it.

**Comment by b1551** [comment]
Can you please document this ? There's no mention in the documentation that "editor.formatOnSave" should be inside php config. I also assumed "editor.formatOnSave" would suffice.

**Comment by RiFi2k** [comment]
It does not require you to nest the format on save setting inside a [php] block to work. But if you don't want to globally turn on formatting on save then this is the best way to have it work scoped to PHP files.

I do see your point though, reading over the docs it's not clear that you would need formatting on save turned on.

**Comment by b1551** [comment]
Actually, it doesn't work if I set it like this: "editor.formatOnSave": true.
I'm under impression @AlexSZYDLO had the same problem. 

Maybe important to note, I'm using phpbf which formats PHP code on save.

**Comment by RiFi2k** [comment]
I'm pretty sure line 40 is just registering the result, boolean, of that setting, but I could see that trying to access the value if it doesn't exist would throw a warning, but I don't think it's going to be a hard error.
I personally run it everyday without the PHP scoped block and don't get an error but possibly its because linux version doesn't care I'm trying to assign a variable to something that doesn't exist?

Anyways, I'll go ahead and check if it's set before assigning it because that is the right thing to do anyways.

Documentation updated BTW.

**Comment by RiFi2k** [comment]
@AlexSZYDLO @b1551 Are you able to check on the latest 1.3.8 version of the extension I just pushed to see if that resolves the issue with checking on the PHP scoped formatOnSave setting? Thanks a bunch if you can make a couple minutes to check.

**Comment by b1551** [comment]
Hm, unfortunately now it's not working in both cases.

**Comment by RiFi2k** [comment]
@b1551 Really because it's working 100% in both cases for me right now, I can revert it though if it's really not working for you at all.

**Comment by b1551** [comment]
Ok, there seems to be a conflict with phpcbf ( https://marketplace.visualstudio.com/items?itemName=persoderlind.vscode-phpcbf ). 
If I disable phpcbf, your extension works flawlessly.

**Comment by b1551** [comment]
Ok, I solved my issue. When using with phpcbf, it's important to set this setting:
"phpcbf.onsave": true

in that case both extensions work very well together.
Thanks @RiFi2k @AlexSZYDLO

**Comment by AlexSZYDLO** [comment]
Sorry I don't see what difference your change at line 40 makes.
I still get the error if "[php]": {"editor.formatOnSave": true} setting is not present (see error message below), which is obvious since you still try to access 'formatOnSave' of something undefined, and I'm pretty sure the script crashes on this

I'd do something like:
`
const config = vscode.workspace.getConfiguration();	    
const phpConfig = config .get('[php]');
    if (config.editor.formatOnSave === true || (phpConfig && phpConfig.editor.formatOnSave === true )) {}
`
This works on my system


Message from extension host output in VS code:

[exthost] [error] TypeError: Cannot read property 'editor.formatOnSave' of undefined
	at DocumentWatcher.<anonymous> (C:\Users\Alexandre\.vscode\extensions\rifi2k.format-html-in-php-1.3.8\out\extension.js:36:79)
	at Generator.next (<anonymous>)
	at C:\Users\Alexandre\.vscode\extensions\rifi2k.format-html-in-php-1.3.8\out\extension.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Alexandre\.vscode\extensions\rifi2k.format-html-in-php-1.3.8\out\extension.js:3:12)
	at DocumentWatcher.doPreSaveTransformations (C:\Users\Alexandre\.vscode\extensions\rifi2k.format-html-in-php-1.3.8\out\extension.js:34:16)
	at DocumentWatcher.<anonymous> (C:\Users\Alexandre\.vscode\extensions\rifi2k.format-html-in-php-1.3.8\out\extension.js:21:46)
	at Generator.next (<anonymous>)
...........................
